name: Data 
description: Issues relating to missing or incorrect data
title: "[DATA] <Short description>"
labels: ["data"]
body:

- type: input
  attributes:
    label: Data In Question
    description: Name of data or datafile that needs to be added/reviewed
    placeholder: "ie. Capital costs for nuclear power plants"
  validations:
    required: true

- type: input
  attributes:
    label: Does the data in question have an existing issue?
    description: To refer to a an existing bug, you can use `#bugid`
    placeholder: "#bugid 10"
  validations:
    required: false

- type: textarea
  attributes:
    label: Issue
    description: Detailed description the issue with the data.
    placeholder: |
      "No capital costs for nuclear power plants exist in the file `weo_2018_powerplant_costs.csv`"
  validations:
    required: true

- type: textarea
  attributes:
    label: Suggested Source
    description: Do you have an source for the data? Please include the URL. 
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional Info
    description: |
      Please provide any additional information or resources that will help us implement the idea. 
  validations:
    required: false
